language: node_js

sudo: required

services:
  - postgresql
  - redis-server

node_js:
    - '10.14.2'

env:
    - CXX=g++-6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6

cache:
    directories:
        - node_modules

before_script:
    - export TZ="Europe/Paris"
    - export NODE_ENV=test
    - export CXX="g++-6"
    - sleep 3
    - npm install -g node-gyp
    - npm install -g yarn
    - make install

script:
  make test
